// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package demo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LiffRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiffRequest) Reset()         { *m = LiffRequest{} }
func (m *LiffRequest) String() string { return proto.CompactTextString(m) }
func (*LiffRequest) ProtoMessage()    {}
func (*LiffRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *LiffRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiffRequest.Unmarshal(m, b)
}
func (m *LiffRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiffRequest.Marshal(b, m, deterministic)
}
func (m *LiffRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiffRequest.Merge(m, src)
}
func (m *LiffRequest) XXX_Size() int {
	return xxx_messageInfo_LiffRequest.Size(m)
}
func (m *LiffRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LiffRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LiffRequest proto.InternalMessageInfo

func (m *LiffRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type LiffResponse struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Definition           string   `protobuf:"bytes,2,opt,name=Definition,proto3" json:"Definition,omitempty"`
	NodeID               string   `protobuf:"bytes,3,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiffResponse) Reset()         { *m = LiffResponse{} }
func (m *LiffResponse) String() string { return proto.CompactTextString(m) }
func (*LiffResponse) ProtoMessage()    {}
func (*LiffResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *LiffResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiffResponse.Unmarshal(m, b)
}
func (m *LiffResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiffResponse.Marshal(b, m, deterministic)
}
func (m *LiffResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiffResponse.Merge(m, src)
}
func (m *LiffResponse) XXX_Size() int {
	return xxx_messageInfo_LiffResponse.Size(m)
}
func (m *LiffResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LiffResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LiffResponse proto.InternalMessageInfo

func (m *LiffResponse) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *LiffResponse) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

func (m *LiffResponse) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func init() {
	proto.RegisterType((*LiffRequest)(nil), "demo.LiffRequest")
	proto.RegisterType((*LiffResponse)(nil), "demo.LiffResponse")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x64, 0xb9, 0xb8, 0x7d, 0x32,
	0xd3, 0xd2, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x98, 0x3c, 0x5d, 0x94, 0xc2, 0xb8, 0x78, 0x20, 0xd2, 0xc5,
	0x05, 0xf9, 0x79, 0xc5, 0xa9, 0xe8, 0xf2, 0x42, 0x72, 0x5c, 0x5c, 0x2e, 0xa9, 0x69, 0x99, 0x79,
	0x99, 0x25, 0x99, 0xf9, 0x79, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x48, 0x22, 0x42, 0x62,
	0x5c, 0x6c, 0x7e, 0xf9, 0x29, 0xa9, 0x9e, 0x2e, 0x12, 0xcc, 0x60, 0x39, 0x28, 0xcf, 0xc8, 0x86,
	0x8b, 0xdb, 0x25, 0x35, 0x37, 0x3f, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x48, 0x97, 0x8b,
	0x05, 0x64, 0x8d, 0x90, 0xa0, 0x1e, 0xd8, 0x81, 0x48, 0x2e, 0x92, 0x12, 0x42, 0x16, 0x82, 0xb8,
	0x22, 0x89, 0x0d, 0xec, 0x03, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0xa7, 0xd8, 0x9e,
	0xcf, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DemoServiceClient is the client API for DemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoServiceClient interface {
	// This method returns a line from one of the Liff books.
	Liff(ctx context.Context, in *LiffRequest, opts ...grpc.CallOption) (*LiffResponse, error)
}

type demoServiceClient struct {
	cc *grpc.ClientConn
}

func NewDemoServiceClient(cc *grpc.ClientConn) DemoServiceClient {
	return &demoServiceClient{cc}
}

func (c *demoServiceClient) Liff(ctx context.Context, in *LiffRequest, opts ...grpc.CallOption) (*LiffResponse, error) {
	out := new(LiffResponse)
	err := c.cc.Invoke(ctx, "/demo.DemoService/Liff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoServiceServer is the server API for DemoService service.
type DemoServiceServer interface {
	// This method returns a line from one of the Liff books.
	Liff(context.Context, *LiffRequest) (*LiffResponse, error)
}

func RegisterDemoServiceServer(s *grpc.Server, srv DemoServiceServer) {
	s.RegisterService(&_DemoService_serviceDesc, srv)
}

func _DemoService_Liff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).Liff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.DemoService/Liff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).Liff(ctx, req.(*LiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DemoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "demo.DemoService",
	HandlerType: (*DemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Liff",
			Handler:    _DemoService_Liff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
