// Code generated by protoc-gen-go. DO NOT EDIT.
// source: management.proto

package clustermgmt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error_Code int32

const (
	Error_OK         Error_Code = 0
	Error_INVALID    Error_Code = 1
	Error_NO_LEADER  Error_Code = 2
	Error_GENERIC    Error_Code = 3
	Error_UNKNOWN_ID Error_Code = 4
)

var Error_Code_name = map[int32]string{
	0: "OK",
	1: "INVALID",
	2: "NO_LEADER",
	3: "GENERIC",
	4: "UNKNOWN_ID",
}

var Error_Code_value = map[string]int32{
	"OK":         0,
	"INVALID":    1,
	"NO_LEADER":  2,
	"GENERIC":    3,
	"UNKNOWN_ID": 4,
}

func (x Error_Code) String() string {
	return proto.EnumName(Error_Code_name, int32(x))
}

func (Error_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{0, 0}
}

type NodeInfo_NodeKind int32

const (
	NodeInfo_LEADER    NodeInfo_NodeKind = 0
	NodeInfo_VOTER     NodeInfo_NodeKind = 1
	NodeInfo_NONVOTER  NodeInfo_NodeKind = 2
	NodeInfo_NONMEMBER NodeInfo_NodeKind = 3
)

var NodeInfo_NodeKind_name = map[int32]string{
	0: "LEADER",
	1: "VOTER",
	2: "NONVOTER",
	3: "NONMEMBER",
}

var NodeInfo_NodeKind_value = map[string]int32{
	"LEADER":    0,
	"VOTER":     1,
	"NONVOTER":  2,
	"NONMEMBER": 3,
}

func (x NodeInfo_NodeKind) String() string {
	return proto.EnumName(NodeInfo_NodeKind_name, int32(x))
}

func (NodeInfo_NodeKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{3, 0}
}

// Errors is the various error codes that might be returned. The values are
// should be fairly obvious.
type Error struct {
	ErrorCode            Error_Code `protobuf:"varint,1,opt,name=ErrorCode,proto3,enum=clustermgmt.Error_Code" json:"ErrorCode,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetErrorCode() Error_Code {
	if m != nil {
		return m.ErrorCode
	}
	return Error_OK
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// GetStatusRequest
type GetStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{1}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

// GetStatusResponse
type GetStatusResponse struct {
	LocalNodeId          string   `protobuf:"bytes,1,opt,name=LocalNodeId,proto3" json:"LocalNodeId,omitempty"`
	LeaderNodeId         string   `protobuf:"bytes,2,opt,name=LeaderNodeId,proto3" json:"LeaderNodeId,omitempty"`
	RaftNodeCount        int32    `protobuf:"varint,3,opt,name=RaftNodeCount,proto3" json:"RaftNodeCount,omitempty"`
	SerfNodeCount        int32    `protobuf:"varint,4,opt,name=SerfNodeCount,proto3" json:"SerfNodeCount,omitempty"`
	LocalRole            string   `protobuf:"bytes,5,opt,name=LocalRole,proto3" json:"LocalRole,omitempty"`
	LocalState           string   `protobuf:"bytes,6,opt,name=LocalState,proto3" json:"LocalState,omitempty"`
	ClusterName          string   `protobuf:"bytes,7,opt,name=ClusterName,proto3" json:"ClusterName,omitempty"`
	ShardCount           int32    `protobuf:"varint,8,opt,name=ShardCount,proto3" json:"ShardCount,omitempty"`
	ShardWeight          int32    `protobuf:"varint,9,opt,name=ShardWeight,proto3" json:"ShardWeight,omitempty"`
	Error                *Error   `protobuf:"bytes,10,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{2}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetLocalNodeId() string {
	if m != nil {
		return m.LocalNodeId
	}
	return ""
}

func (m *GetStatusResponse) GetLeaderNodeId() string {
	if m != nil {
		return m.LeaderNodeId
	}
	return ""
}

func (m *GetStatusResponse) GetRaftNodeCount() int32 {
	if m != nil {
		return m.RaftNodeCount
	}
	return 0
}

func (m *GetStatusResponse) GetSerfNodeCount() int32 {
	if m != nil {
		return m.SerfNodeCount
	}
	return 0
}

func (m *GetStatusResponse) GetLocalRole() string {
	if m != nil {
		return m.LocalRole
	}
	return ""
}

func (m *GetStatusResponse) GetLocalState() string {
	if m != nil {
		return m.LocalState
	}
	return ""
}

func (m *GetStatusResponse) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *GetStatusResponse) GetShardCount() int32 {
	if m != nil {
		return m.ShardCount
	}
	return 0
}

func (m *GetStatusResponse) GetShardWeight() int32 {
	if m != nil {
		return m.ShardWeight
	}
	return 0
}

func (m *GetStatusResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

// NodeInfo contains information on a single node in the cluster/swarm
type NodeInfo struct {
	// NodeId is the node's identifier.
	NodeId               string            `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Kind                 NodeInfo_NodeKind `protobuf:"varint,2,opt,name=Kind,proto3,enum=clustermgmt.NodeInfo_NodeKind" json:"Kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{3}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NodeInfo) GetKind() NodeInfo_NodeKind {
	if m != nil {
		return m.Kind
	}
	return NodeInfo_LEADER
}

// ListNodesRequest
type ListNodesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNodesRequest) Reset()         { *m = ListNodesRequest{} }
func (m *ListNodesRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodesRequest) ProtoMessage()    {}
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{4}
}

func (m *ListNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesRequest.Unmarshal(m, b)
}
func (m *ListNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesRequest.Marshal(b, m, deterministic)
}
func (m *ListNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesRequest.Merge(m, src)
}
func (m *ListNodesRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodesRequest.Size(m)
}
func (m *ListNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesRequest proto.InternalMessageInfo

// ListNodesResponse is the response to a ListSerfNodes call. The number of
// Serf nodes will initially be quite small so we won't need a stream response
// here.
type ListNodesResponse struct {
	NodeId               string      `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Nodes                []*NodeInfo `protobuf:"bytes,2,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	Error                *Error      `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListNodesResponse) Reset()         { *m = ListNodesResponse{} }
func (m *ListNodesResponse) String() string { return proto.CompactTextString(m) }
func (*ListNodesResponse) ProtoMessage()    {}
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{5}
}

func (m *ListNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesResponse.Unmarshal(m, b)
}
func (m *ListNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesResponse.Marshal(b, m, deterministic)
}
func (m *ListNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesResponse.Merge(m, src)
}
func (m *ListNodesResponse) XXX_Size() int {
	return xxx_messageInfo_ListNodesResponse.Size(m)
}
func (m *ListNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesResponse proto.InternalMessageInfo

func (m *ListNodesResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ListNodesResponse) GetNodes() []*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ListNodesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type EndpointRequest struct {
	EndpointName         string   `protobuf:"bytes,1,opt,name=EndpointName,proto3" json:"EndpointName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndpointRequest) Reset()         { *m = EndpointRequest{} }
func (m *EndpointRequest) String() string { return proto.CompactTextString(m) }
func (*EndpointRequest) ProtoMessage()    {}
func (*EndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{6}
}

func (m *EndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointRequest.Unmarshal(m, b)
}
func (m *EndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointRequest.Marshal(b, m, deterministic)
}
func (m *EndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointRequest.Merge(m, src)
}
func (m *EndpointRequest) XXX_Size() int {
	return xxx_messageInfo_EndpointRequest.Size(m)
}
func (m *EndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointRequest proto.InternalMessageInfo

func (m *EndpointRequest) GetEndpointName() string {
	if m != nil {
		return m.EndpointName
	}
	return ""
}

type EndpointInfo struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	HostPort             string   `protobuf:"bytes,2,opt,name=HostPort,proto3" json:"HostPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndpointInfo) Reset()         { *m = EndpointInfo{} }
func (m *EndpointInfo) String() string { return proto.CompactTextString(m) }
func (*EndpointInfo) ProtoMessage()    {}
func (*EndpointInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{7}
}

func (m *EndpointInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointInfo.Unmarshal(m, b)
}
func (m *EndpointInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointInfo.Marshal(b, m, deterministic)
}
func (m *EndpointInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointInfo.Merge(m, src)
}
func (m *EndpointInfo) XXX_Size() int {
	return xxx_messageInfo_EndpointInfo.Size(m)
}
func (m *EndpointInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointInfo proto.InternalMessageInfo

func (m *EndpointInfo) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *EndpointInfo) GetHostPort() string {
	if m != nil {
		return m.HostPort
	}
	return ""
}

type EndpointResponse struct {
	NodeId               string          `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Error                *Error          `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Endpoints            []*EndpointInfo `protobuf:"bytes,3,rep,name=Endpoints,proto3" json:"Endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EndpointResponse) Reset()         { *m = EndpointResponse{} }
func (m *EndpointResponse) String() string { return proto.CompactTextString(m) }
func (*EndpointResponse) ProtoMessage()    {}
func (*EndpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{8}
}

func (m *EndpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointResponse.Unmarshal(m, b)
}
func (m *EndpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointResponse.Marshal(b, m, deterministic)
}
func (m *EndpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointResponse.Merge(m, src)
}
func (m *EndpointResponse) XXX_Size() int {
	return xxx_messageInfo_EndpointResponse.Size(m)
}
func (m *EndpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointResponse proto.InternalMessageInfo

func (m *EndpointResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *EndpointResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *EndpointResponse) GetEndpoints() []*EndpointInfo {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

// Messages for the AddNode method
type AddNodeRequest struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeRequest) Reset()         { *m = AddNodeRequest{} }
func (m *AddNodeRequest) String() string { return proto.CompactTextString(m) }
func (*AddNodeRequest) ProtoMessage()    {}
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{9}
}

func (m *AddNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeRequest.Unmarshal(m, b)
}
func (m *AddNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeRequest.Marshal(b, m, deterministic)
}
func (m *AddNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeRequest.Merge(m, src)
}
func (m *AddNodeRequest) XXX_Size() int {
	return xxx_messageInfo_AddNodeRequest.Size(m)
}
func (m *AddNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeRequest proto.InternalMessageInfo

func (m *AddNodeRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

// AddNodeResponse
type AddNodeResponse struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeResponse) Reset()         { *m = AddNodeResponse{} }
func (m *AddNodeResponse) String() string { return proto.CompactTextString(m) }
func (*AddNodeResponse) ProtoMessage()    {}
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{10}
}

func (m *AddNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeResponse.Unmarshal(m, b)
}
func (m *AddNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeResponse.Marshal(b, m, deterministic)
}
func (m *AddNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeResponse.Merge(m, src)
}
func (m *AddNodeResponse) XXX_Size() int {
	return xxx_messageInfo_AddNodeResponse.Size(m)
}
func (m *AddNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeResponse proto.InternalMessageInfo

func (m *AddNodeResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *AddNodeResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

// RemoveNodeRequest
type RemoveNodeRequest struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodeRequest) Reset()         { *m = RemoveNodeRequest{} }
func (m *RemoveNodeRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveNodeRequest) ProtoMessage()    {}
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{11}
}

func (m *RemoveNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodeRequest.Unmarshal(m, b)
}
func (m *RemoveNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodeRequest.Marshal(b, m, deterministic)
}
func (m *RemoveNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodeRequest.Merge(m, src)
}
func (m *RemoveNodeRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveNodeRequest.Size(m)
}
func (m *RemoveNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodeRequest proto.InternalMessageInfo

func (m *RemoveNodeRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

// RemoveNodeResponse
type RemoveNodeResponse struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodeResponse) Reset()         { *m = RemoveNodeResponse{} }
func (m *RemoveNodeResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveNodeResponse) ProtoMessage()    {}
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{12}
}

func (m *RemoveNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodeResponse.Unmarshal(m, b)
}
func (m *RemoveNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodeResponse.Marshal(b, m, deterministic)
}
func (m *RemoveNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodeResponse.Merge(m, src)
}
func (m *RemoveNodeResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveNodeResponse.Size(m)
}
func (m *RemoveNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodeResponse proto.InternalMessageInfo

func (m *RemoveNodeResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *RemoveNodeResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

// ListShardsRequest
type ListShardsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListShardsRequest) Reset()         { *m = ListShardsRequest{} }
func (m *ListShardsRequest) String() string { return proto.CompactTextString(m) }
func (*ListShardsRequest) ProtoMessage()    {}
func (*ListShardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{13}
}

func (m *ListShardsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShardsRequest.Unmarshal(m, b)
}
func (m *ListShardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShardsRequest.Marshal(b, m, deterministic)
}
func (m *ListShardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShardsRequest.Merge(m, src)
}
func (m *ListShardsRequest) XXX_Size() int {
	return xxx_messageInfo_ListShardsRequest.Size(m)
}
func (m *ListShardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListShardsRequest proto.InternalMessageInfo

// ListShardsResponse
type ListShardsResponse struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListShardsResponse) Reset()         { *m = ListShardsResponse{} }
func (m *ListShardsResponse) String() string { return proto.CompactTextString(m) }
func (*ListShardsResponse) ProtoMessage()    {}
func (*ListShardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{14}
}

func (m *ListShardsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShardsResponse.Unmarshal(m, b)
}
func (m *ListShardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShardsResponse.Marshal(b, m, deterministic)
}
func (m *ListShardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShardsResponse.Merge(m, src)
}
func (m *ListShardsResponse) XXX_Size() int {
	return xxx_messageInfo_ListShardsResponse.Size(m)
}
func (m *ListShardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListShardsResponse proto.InternalMessageInfo

func (m *ListShardsResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ListShardsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type StepDownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StepDownRequest) Reset()         { *m = StepDownRequest{} }
func (m *StepDownRequest) String() string { return proto.CompactTextString(m) }
func (*StepDownRequest) ProtoMessage()    {}
func (*StepDownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{15}
}

func (m *StepDownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepDownRequest.Unmarshal(m, b)
}
func (m *StepDownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepDownRequest.Marshal(b, m, deterministic)
}
func (m *StepDownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepDownRequest.Merge(m, src)
}
func (m *StepDownRequest) XXX_Size() int {
	return xxx_messageInfo_StepDownRequest.Size(m)
}
func (m *StepDownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StepDownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StepDownRequest proto.InternalMessageInfo

type StepDownResponse struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StepDownResponse) Reset()         { *m = StepDownResponse{} }
func (m *StepDownResponse) String() string { return proto.CompactTextString(m) }
func (*StepDownResponse) ProtoMessage()    {}
func (*StepDownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edc174f991dc0a25, []int{16}
}

func (m *StepDownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepDownResponse.Unmarshal(m, b)
}
func (m *StepDownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepDownResponse.Marshal(b, m, deterministic)
}
func (m *StepDownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepDownResponse.Merge(m, src)
}
func (m *StepDownResponse) XXX_Size() int {
	return xxx_messageInfo_StepDownResponse.Size(m)
}
func (m *StepDownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StepDownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StepDownResponse proto.InternalMessageInfo

func (m *StepDownResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *StepDownResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterEnum("clustermgmt.Error_Code", Error_Code_name, Error_Code_value)
	proto.RegisterEnum("clustermgmt.NodeInfo_NodeKind", NodeInfo_NodeKind_name, NodeInfo_NodeKind_value)
	proto.RegisterType((*Error)(nil), "clustermgmt.Error")
	proto.RegisterType((*GetStatusRequest)(nil), "clustermgmt.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "clustermgmt.GetStatusResponse")
	proto.RegisterType((*NodeInfo)(nil), "clustermgmt.NodeInfo")
	proto.RegisterType((*ListNodesRequest)(nil), "clustermgmt.ListNodesRequest")
	proto.RegisterType((*ListNodesResponse)(nil), "clustermgmt.ListNodesResponse")
	proto.RegisterType((*EndpointRequest)(nil), "clustermgmt.EndpointRequest")
	proto.RegisterType((*EndpointInfo)(nil), "clustermgmt.EndpointInfo")
	proto.RegisterType((*EndpointResponse)(nil), "clustermgmt.EndpointResponse")
	proto.RegisterType((*AddNodeRequest)(nil), "clustermgmt.AddNodeRequest")
	proto.RegisterType((*AddNodeResponse)(nil), "clustermgmt.AddNodeResponse")
	proto.RegisterType((*RemoveNodeRequest)(nil), "clustermgmt.RemoveNodeRequest")
	proto.RegisterType((*RemoveNodeResponse)(nil), "clustermgmt.RemoveNodeResponse")
	proto.RegisterType((*ListShardsRequest)(nil), "clustermgmt.ListShardsRequest")
	proto.RegisterType((*ListShardsResponse)(nil), "clustermgmt.ListShardsResponse")
	proto.RegisterType((*StepDownRequest)(nil), "clustermgmt.StepDownRequest")
	proto.RegisterType((*StepDownResponse)(nil), "clustermgmt.StepDownResponse")
}

func init() { proto.RegisterFile("management.proto", fileDescriptor_edc174f991dc0a25) }

var fileDescriptor_edc174f991dc0a25 = []byte{
	// 747 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4d, 0x6f, 0xda, 0x5a,
	0x10, 0x8d, 0xf9, 0xf6, 0x90, 0x10, 0x33, 0x4f, 0xef, 0x3d, 0x97, 0x26, 0x29, 0xb2, 0xba, 0x40,
	0x8a, 0xc4, 0x82, 0x2a, 0xea, 0xae, 0x52, 0x02, 0x2e, 0x25, 0x80, 0xa9, 0x2e, 0x29, 0x59, 0x46,
	0x6e, 0x7c, 0x43, 0x90, 0x82, 0x2f, 0xb5, 0x2f, 0xed, 0xbe, 0xfb, 0x6e, 0xbb, 0xef, 0xa2, 0x3f,
	0xb0, 0xff, 0xa0, 0xf2, 0xf5, 0xb7, 0x09, 0x4d, 0x17, 0xec, 0x3c, 0x67, 0x8e, 0x67, 0xce, 0xcc,
	0x3d, 0xbe, 0x00, 0xca, 0xd2, 0xb4, 0xcd, 0x39, 0x5d, 0x52, 0x9b, 0xb7, 0x57, 0x0e, 0xe3, 0x0c,
	0xab, 0xb7, 0x0f, 0x6b, 0x97, 0x53, 0x67, 0x39, 0x5f, 0x72, 0xed, 0x87, 0x04, 0x45, 0xdd, 0x71,
	0x98, 0x83, 0x67, 0x20, 0x8b, 0x87, 0x2e, 0xb3, 0xa8, 0x2a, 0x35, 0xa5, 0x56, 0xad, 0xf3, 0x7f,
	0x3b, 0x41, 0x6d, 0x8b, 0x6c, 0xdb, 0x4b, 0x93, 0x98, 0x89, 0x2a, 0x94, 0xc7, 0xd4, 0x75, 0xcd,
	0x39, 0x55, 0x73, 0x4d, 0xa9, 0x25, 0x93, 0x30, 0xd4, 0xfa, 0x50, 0x10, 0x8c, 0x12, 0xe4, 0x26,
	0x43, 0x65, 0x0f, 0xab, 0x50, 0x1e, 0x18, 0xb3, 0xf3, 0xd1, 0xa0, 0xa7, 0x48, 0x78, 0x00, 0xb2,
	0x31, 0xb9, 0x19, 0xe9, 0xe7, 0x3d, 0x9d, 0x28, 0x39, 0x2f, 0xd7, 0xd7, 0x0d, 0x9d, 0x0c, 0xba,
	0x4a, 0x1e, 0x6b, 0x00, 0x1f, 0x8c, 0xa1, 0x31, 0xb9, 0x36, 0x6e, 0x06, 0x3d, 0xa5, 0xa0, 0x21,
	0x28, 0x7d, 0xca, 0xa7, 0xdc, 0xe4, 0x6b, 0x97, 0xd0, 0x4f, 0x6b, 0xea, 0x72, 0xed, 0x57, 0x0e,
	0xea, 0x09, 0xd0, 0x5d, 0x31, 0xdb, 0xa5, 0xd8, 0x84, 0xea, 0x88, 0xdd, 0x9a, 0x0f, 0x06, 0xb3,
	0xe8, 0xc0, 0x12, 0x53, 0xc8, 0x24, 0x09, 0xa1, 0x06, 0xfb, 0x23, 0x6a, 0x5a, 0xd4, 0x09, 0x28,
	0xbe, 0xe6, 0x14, 0x86, 0x2f, 0xe1, 0x80, 0x98, 0x77, 0xdc, 0x8b, 0xba, 0x6c, 0x6d, 0x73, 0x35,
	0xdf, 0x94, 0x5a, 0x45, 0x92, 0x06, 0x3d, 0xd6, 0x94, 0x3a, 0x77, 0x31, 0xab, 0xe0, 0xb3, 0x52,
	0x20, 0x1e, 0x81, 0x2c, 0xda, 0x13, 0xf6, 0x40, 0xd5, 0xa2, 0x68, 0x16, 0x03, 0x78, 0x02, 0x20,
	0x02, 0x6f, 0x0c, 0xaa, 0x96, 0x44, 0x3a, 0x81, 0x78, 0xf3, 0x74, 0xfd, 0x13, 0x30, 0xcc, 0x25,
	0x55, 0xcb, 0xfe, 0x3c, 0x09, 0xc8, 0xab, 0x30, 0xbd, 0x37, 0x1d, 0xcb, 0x97, 0x50, 0x11, 0x12,
	0x12, 0x88, 0x57, 0x41, 0x44, 0xd7, 0x74, 0x31, 0xbf, 0xe7, 0xaa, 0x2c, 0x08, 0x49, 0x08, 0x5b,
	0x81, 0x01, 0x54, 0x68, 0x4a, 0xad, 0x6a, 0x07, 0x37, 0xcf, 0x9c, 0xf8, 0x04, 0xed, 0xbb, 0x04,
	0x15, 0xb1, 0x22, 0xfb, 0x8e, 0xe1, 0x7f, 0x50, 0x4a, 0x6d, 0x39, 0x88, 0xb0, 0x03, 0x85, 0xe1,
	0xc2, 0xf6, 0x17, 0x5b, 0xeb, 0x9c, 0xa4, 0xaa, 0x85, 0x2f, 0x8b, 0x07, 0x8f, 0x45, 0x04, 0x57,
	0x7b, 0xe3, 0xd7, 0xf5, 0x9e, 0x11, 0xa0, 0x14, 0xb8, 0x62, 0x0f, 0x65, 0x28, 0xce, 0x26, 0x57,
	0x3a, 0x51, 0x24, 0xdc, 0x87, 0x8a, 0x31, 0x31, 0xfc, 0x28, 0xe7, 0xbb, 0xc7, 0x18, 0xeb, 0xe3,
	0x0b, 0x9d, 0x28, 0x79, 0xcf, 0x20, 0xa3, 0x85, 0x2b, 0xce, 0x26, 0x32, 0xc8, 0x57, 0x09, 0xea,
	0x09, 0x30, 0x30, 0xc8, 0x36, 0xd5, 0xa7, 0x50, 0x14, 0x44, 0x35, 0xd7, 0xcc, 0xb7, 0xaa, 0x9d,
	0x7f, 0x1f, 0x95, 0x4d, 0x7c, 0x4e, 0xbc, 0xb1, 0xfc, 0x53, 0x1b, 0x3b, 0x83, 0x43, 0xdd, 0xb6,
	0x56, 0x6c, 0x61, 0xf3, 0x40, 0x97, 0x67, 0xc0, 0x10, 0x12, 0x67, 0xea, 0xeb, 0x48, 0x61, 0xda,
	0x45, 0xcc, 0xf9, 0xe3, 0xae, 0x1b, 0x50, 0x79, 0xc7, 0x5c, 0xfe, 0x9e, 0x39, 0x3c, 0x30, 0x72,
	0x14, 0x6b, 0xdf, 0x24, 0x50, 0xe2, 0xde, 0x4f, 0x8c, 0x1f, 0x4d, 0x94, 0x7b, 0x62, 0x22, 0x7c,
	0x0d, 0x72, 0x58, 0xd5, 0x55, 0xf3, 0x62, 0x59, 0xcf, 0xd2, 0xec, 0x84, 0x70, 0x12, 0x73, 0xb5,
	0x16, 0xd4, 0xce, 0x2d, 0xcb, 0xeb, 0x17, 0x6e, 0x62, 0x8b, 0x18, 0x6d, 0x0a, 0x87, 0x11, 0x73,
	0x57, 0xba, 0xb5, 0x53, 0xa8, 0x13, 0xba, 0x64, 0x9f, 0xe9, 0xdf, 0x28, 0x98, 0x01, 0x26, 0xc9,
	0x3b, 0x13, 0xf1, 0x8f, 0x6f, 0x49, 0xf1, 0xf5, 0x45, 0x46, 0x9d, 0x01, 0x26, 0xc1, 0x9d, 0x35,
	0xab, 0xc3, 0xe1, 0x94, 0xd3, 0x55, 0x8f, 0x7d, 0xb1, 0xc3, 0x56, 0x57, 0xa0, 0xc4, 0xd0, 0xae,
	0x1a, 0x75, 0x7e, 0x16, 0xa0, 0x1e, 0x5c, 0x49, 0xe3, 0xe8, 0xb7, 0x06, 0x2f, 0x41, 0x8e, 0xee,
	0x67, 0x3c, 0x4e, 0xbd, 0x9d, 0xbd, 0xcc, 0x1b, 0x27, 0xdb, 0xd2, 0x81, 0xc6, 0x4b, 0x90, 0xa3,
	0x4f, 0x39, 0x53, 0x2b, 0xfb, 0xdd, 0x67, 0x6a, 0x6d, 0xde, 0x00, 0x43, 0xd8, 0x7f, 0xbb, 0xb0,
	0xad, 0xd0, 0x98, 0x78, 0xf4, 0xa8, 0x7b, 0xc3, 0x6a, 0xc7, 0x5b, 0xb2, 0x41, 0xb1, 0x1e, 0x94,
	0x03, 0xab, 0xe2, 0xf3, 0x14, 0x33, 0x6d, 0xf5, 0xc6, 0xd1, 0xe3, 0xc9, 0xa0, 0xca, 0x18, 0x20,
	0xb6, 0x1b, 0xa6, 0x07, 0xd8, 0x30, 0x6d, 0xe3, 0xc5, 0xd6, 0x7c, 0x50, 0xae, 0x0f, 0x95, 0xf0,
	0x94, 0x33, 0xd3, 0x65, 0xfc, 0x90, 0x99, 0x6e, 0xc3, 0x1a, 0x63, 0x80, 0xd8, 0x99, 0xb8, 0xb9,
	0xd8, 0x94, 0x8f, 0x33, 0xba, 0x36, 0x2d, 0xfd, 0xb1, 0x24, 0xfe, 0x7e, 0xbc, 0xfa, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x33, 0xe5, 0x87, 0x3e, 0x92, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterManagementClient is the client API for ClusterManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterManagementClient interface {
	// GetState returns the cluster state of the local node.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// ListNodes lists the known nodes in the cluster, as seen by the leader.
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// FindEndpoint looks up an endpoint and returns the list. The list is
	// retrieved from the local node.
	FindEndpoint(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*EndpointResponse, error)
	// AddNode adds a node to the cluster. This request is proxied to the leader
	// if it is received by a non-leader node. The request will fail if there's
	// no current leader in the cluster.
	AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*AddNodeResponse, error)
	// RemoveNode removes a node from the cluster. This request is handled by
	// the leader. If the request is sent to one of the non-leaders in the cluster
	// it will be proxied to the leader.
	RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*RemoveNodeResponse, error)
	// StepDown causes the (Raft) leader to step down and a new leader will be elected.
	StepDown(ctx context.Context, in *StepDownRequest, opts ...grpc.CallOption) (*StepDownResponse, error)
	// ListShards dumps the current shard map as seen by the node handling the
	// request.
	ListShards(ctx context.Context, in *ListShardsRequest, opts ...grpc.CallOption) (*ListShardsResponse, error)
}

type clusterManagementClient struct {
	cc *grpc.ClientConn
}

func NewClusterManagementClient(cc *grpc.ClientConn) ClusterManagementClient {
	return &clusterManagementClient{cc}
}

func (c *clusterManagementClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/clustermgmt.ClusterManagement/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterManagementClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, "/clustermgmt.ClusterManagement/ListNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterManagementClient) FindEndpoint(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*EndpointResponse, error) {
	out := new(EndpointResponse)
	err := c.cc.Invoke(ctx, "/clustermgmt.ClusterManagement/FindEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterManagementClient) AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*AddNodeResponse, error) {
	out := new(AddNodeResponse)
	err := c.cc.Invoke(ctx, "/clustermgmt.ClusterManagement/AddNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterManagementClient) RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*RemoveNodeResponse, error) {
	out := new(RemoveNodeResponse)
	err := c.cc.Invoke(ctx, "/clustermgmt.ClusterManagement/RemoveNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterManagementClient) StepDown(ctx context.Context, in *StepDownRequest, opts ...grpc.CallOption) (*StepDownResponse, error) {
	out := new(StepDownResponse)
	err := c.cc.Invoke(ctx, "/clustermgmt.ClusterManagement/StepDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterManagementClient) ListShards(ctx context.Context, in *ListShardsRequest, opts ...grpc.CallOption) (*ListShardsResponse, error) {
	out := new(ListShardsResponse)
	err := c.cc.Invoke(ctx, "/clustermgmt.ClusterManagement/ListShards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterManagementServer is the server API for ClusterManagement service.
type ClusterManagementServer interface {
	// GetState returns the cluster state of the local node.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// ListNodes lists the known nodes in the cluster, as seen by the leader.
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// FindEndpoint looks up an endpoint and returns the list. The list is
	// retrieved from the local node.
	FindEndpoint(context.Context, *EndpointRequest) (*EndpointResponse, error)
	// AddNode adds a node to the cluster. This request is proxied to the leader
	// if it is received by a non-leader node. The request will fail if there's
	// no current leader in the cluster.
	AddNode(context.Context, *AddNodeRequest) (*AddNodeResponse, error)
	// RemoveNode removes a node from the cluster. This request is handled by
	// the leader. If the request is sent to one of the non-leaders in the cluster
	// it will be proxied to the leader.
	RemoveNode(context.Context, *RemoveNodeRequest) (*RemoveNodeResponse, error)
	// StepDown causes the (Raft) leader to step down and a new leader will be elected.
	StepDown(context.Context, *StepDownRequest) (*StepDownResponse, error)
	// ListShards dumps the current shard map as seen by the node handling the
	// request.
	ListShards(context.Context, *ListShardsRequest) (*ListShardsResponse, error)
}

func RegisterClusterManagementServer(s *grpc.Server, srv ClusterManagementServer) {
	s.RegisterService(&_ClusterManagement_serviceDesc, srv)
}

func _ClusterManagement_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterManagementServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clustermgmt.ClusterManagement/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterManagementServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterManagement_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterManagementServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clustermgmt.ClusterManagement/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterManagementServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterManagement_FindEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterManagementServer).FindEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clustermgmt.ClusterManagement/FindEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterManagementServer).FindEndpoint(ctx, req.(*EndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterManagement_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterManagementServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clustermgmt.ClusterManagement/AddNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterManagementServer).AddNode(ctx, req.(*AddNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterManagement_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterManagementServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clustermgmt.ClusterManagement/RemoveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterManagementServer).RemoveNode(ctx, req.(*RemoveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterManagement_StepDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterManagementServer).StepDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clustermgmt.ClusterManagement/StepDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterManagementServer).StepDown(ctx, req.(*StepDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterManagement_ListShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterManagementServer).ListShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clustermgmt.ClusterManagement/ListShards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterManagementServer).ListShards(ctx, req.(*ListShardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clustermgmt.ClusterManagement",
	HandlerType: (*ClusterManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _ClusterManagement_GetStatus_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _ClusterManagement_ListNodes_Handler,
		},
		{
			MethodName: "FindEndpoint",
			Handler:    _ClusterManagement_FindEndpoint_Handler,
		},
		{
			MethodName: "AddNode",
			Handler:    _ClusterManagement_AddNode_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _ClusterManagement_RemoveNode_Handler,
		},
		{
			MethodName: "StepDown",
			Handler:    _ClusterManagement_StepDown_Handler,
		},
		{
			MethodName: "ListShards",
			Handler:    _ClusterManagement_ListShards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management.proto",
}
