// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sharding.proto

package shardpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WireNodes struct {
	NodeId               int32    `protobuf:"varint,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	NodeName             string   `protobuf:"bytes,2,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WireNodes) Reset()         { *m = WireNodes{} }
func (m *WireNodes) String() string { return proto.CompactTextString(m) }
func (*WireNodes) ProtoMessage()    {}
func (*WireNodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_65fd85df55b7d210, []int{0}
}

func (m *WireNodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WireNodes.Unmarshal(m, b)
}
func (m *WireNodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WireNodes.Marshal(b, m, deterministic)
}
func (m *WireNodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WireNodes.Merge(m, src)
}
func (m *WireNodes) XXX_Size() int {
	return xxx_messageInfo_WireNodes.Size(m)
}
func (m *WireNodes) XXX_DiscardUnknown() {
	xxx_messageInfo_WireNodes.DiscardUnknown(m)
}

var xxx_messageInfo_WireNodes proto.InternalMessageInfo

func (m *WireNodes) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *WireNodes) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

type WireShard struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Weight               int32    `protobuf:"varint,2,opt,name=Weight,proto3" json:"Weight,omitempty"`
	NodeId               int32    `protobuf:"varint,3,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WireShard) Reset()         { *m = WireShard{} }
func (m *WireShard) String() string { return proto.CompactTextString(m) }
func (*WireShard) ProtoMessage()    {}
func (*WireShard) Descriptor() ([]byte, []int) {
	return fileDescriptor_65fd85df55b7d210, []int{1}
}

func (m *WireShard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WireShard.Unmarshal(m, b)
}
func (m *WireShard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WireShard.Marshal(b, m, deterministic)
}
func (m *WireShard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WireShard.Merge(m, src)
}
func (m *WireShard) XXX_Size() int {
	return xxx_messageInfo_WireShard.Size(m)
}
func (m *WireShard) XXX_DiscardUnknown() {
	xxx_messageInfo_WireShard.DiscardUnknown(m)
}

var xxx_messageInfo_WireShard proto.InternalMessageInfo

func (m *WireShard) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WireShard) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *WireShard) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type ShardDistribution struct {
	Nodes                []*WireNodes `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	Shards               []*WireShard `protobuf:"bytes,2,rep,name=Shards,proto3" json:"Shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ShardDistribution) Reset()         { *m = ShardDistribution{} }
func (m *ShardDistribution) String() string { return proto.CompactTextString(m) }
func (*ShardDistribution) ProtoMessage()    {}
func (*ShardDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_65fd85df55b7d210, []int{2}
}

func (m *ShardDistribution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardDistribution.Unmarshal(m, b)
}
func (m *ShardDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardDistribution.Marshal(b, m, deterministic)
}
func (m *ShardDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardDistribution.Merge(m, src)
}
func (m *ShardDistribution) XXX_Size() int {
	return xxx_messageInfo_ShardDistribution.Size(m)
}
func (m *ShardDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_ShardDistribution proto.InternalMessageInfo

func (m *ShardDistribution) GetNodes() []*WireNodes {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ShardDistribution) GetShards() []*WireShard {
	if m != nil {
		return m.Shards
	}
	return nil
}

func init() {
	proto.RegisterType((*WireNodes)(nil), "shardpb.WireNodes")
	proto.RegisterType((*WireShard)(nil), "shardpb.WireShard")
	proto.RegisterType((*ShardDistribution)(nil), "shardpb.ShardDistribution")
}

func init() { proto.RegisterFile("sharding.proto", fileDescriptor_65fd85df55b7d210) }

var fileDescriptor_65fd85df55b7d210 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xce, 0x48, 0x2c,
	0x4a, 0xc9, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0xf3, 0x0b, 0x92,
	0x94, 0xec, 0xb9, 0x38, 0xc3, 0x33, 0x8b, 0x52, 0xfd, 0xf2, 0x53, 0x52, 0x8b, 0x85, 0xc4, 0xb8,
	0xd8, 0x40, 0x0c, 0xcf, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x28, 0x4f, 0x48, 0x8a,
	0x8b, 0x03, 0xc4, 0xf2, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3,
	0x95, 0xbc, 0x21, 0x06, 0x04, 0x83, 0xcc, 0x13, 0xe2, 0xe3, 0x62, 0x82, 0x6b, 0x66, 0xf2, 0x4c,
	0x01, 0x19, 0x18, 0x9e, 0x9a, 0x99, 0x9e, 0x51, 0x02, 0xd6, 0xc6, 0x1a, 0x04, 0xe5, 0x21, 0x59,
	0xc4, 0x8c, 0x6c, 0x91, 0x52, 0x26, 0x97, 0x20, 0xd8, 0x20, 0x97, 0xcc, 0xe2, 0x92, 0xa2, 0xcc,
	0xa4, 0xd2, 0x92, 0xcc, 0xfc, 0x3c, 0x21, 0x0d, 0x2e, 0x56, 0xb0, 0xf3, 0x24, 0x18, 0x15, 0x98,
	0x35, 0xb8, 0x8d, 0x84, 0xf4, 0xa0, 0x6e, 0xd7, 0x83, 0x3b, 0x3c, 0x08, 0xa2, 0x40, 0x48, 0x8b,
	0x8b, 0x0d, 0xac, 0xbd, 0x58, 0x82, 0x09, 0x8b, 0x52, 0xb0, 0x54, 0x10, 0x54, 0x45, 0x12, 0x1b,
	0x38, 0x20, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x91, 0xcf, 0x11, 0x1a, 0x01, 0x00,
	0x00,
}
