// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

package clusteproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ConfirmShardMapRequest is sent by followers to the leader to signal readyness
// with the new shard map
type ConfirmShardMapRequest struct {
	LogIndex             int64    `protobuf:"varint,1,opt,name=LogIndex,proto3" json:"LogIndex,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmShardMapRequest) Reset()         { *m = ConfirmShardMapRequest{} }
func (m *ConfirmShardMapRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmShardMapRequest) ProtoMessage()    {}
func (*ConfirmShardMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{0}
}

func (m *ConfirmShardMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmShardMapRequest.Unmarshal(m, b)
}
func (m *ConfirmShardMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmShardMapRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmShardMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmShardMapRequest.Merge(m, src)
}
func (m *ConfirmShardMapRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmShardMapRequest.Size(m)
}
func (m *ConfirmShardMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmShardMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmShardMapRequest proto.InternalMessageInfo

func (m *ConfirmShardMapRequest) GetLogIndex() int64 {
	if m != nil {
		return m.LogIndex
	}
	return 0
}

func (m *ConfirmShardMapRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

// ConfirmShardMapResponse is sent as a response from the leader to the
// followers.
type ConfirmShardMapResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	CurrentIndex         int64    `protobuf:"varint,2,opt,name=CurrentIndex,proto3" json:"CurrentIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmShardMapResponse) Reset()         { *m = ConfirmShardMapResponse{} }
func (m *ConfirmShardMapResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmShardMapResponse) ProtoMessage()    {}
func (*ConfirmShardMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{1}
}

func (m *ConfirmShardMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmShardMapResponse.Unmarshal(m, b)
}
func (m *ConfirmShardMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmShardMapResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmShardMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmShardMapResponse.Merge(m, src)
}
func (m *ConfirmShardMapResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmShardMapResponse.Size(m)
}
func (m *ConfirmShardMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmShardMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmShardMapResponse proto.InternalMessageInfo

func (m *ConfirmShardMapResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ConfirmShardMapResponse) GetCurrentIndex() int64 {
	if m != nil {
		return m.CurrentIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfirmShardMapRequest)(nil), "clusteproto.ConfirmShardMapRequest")
	proto.RegisterType((*ConfirmShardMapResponse)(nil), "clusteproto.ConfirmShardMapResponse")
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor_3cfb3b8ec240c376) }

var fileDescriptor_3cfb3b8ec240c376 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0x29, 0x2d,
	0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x86, 0x70, 0xc1, 0x1c, 0x25,
	0x1f, 0x2e, 0x31, 0xe7, 0xfc, 0xbc, 0xb4, 0xcc, 0xa2, 0xdc, 0xe0, 0x8c, 0xc4, 0xa2, 0x14, 0xdf,
	0xc4, 0x82, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x29, 0x2e, 0x0e, 0x9f, 0xfc, 0x74,
	0xcf, 0xbc, 0x94, 0xd4, 0x0a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x38, 0x5f, 0x48, 0x8c,
	0x8b, 0xcd, 0x2f, 0x3f, 0x25, 0xd5, 0xd3, 0x45, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xca,
	0x53, 0x0a, 0xe7, 0x12, 0xc7, 0x30, 0xad, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x82, 0x8b,
	0x3d, 0xb8, 0x34, 0x39, 0x39, 0xb5, 0xb8, 0x18, 0x6c, 0x1a, 0x47, 0x10, 0x8c, 0x2b, 0xa4, 0xc4,
	0xc5, 0xe3, 0x5c, 0x5a, 0x54, 0x94, 0x9a, 0x57, 0x02, 0xb1, 0x8c, 0x09, 0x6c, 0x19, 0x8a, 0x98,
	0x51, 0x09, 0x97, 0x88, 0x33, 0xc4, 0x13, 0x3e, 0xa9, 0x89, 0x29, 0xa9, 0x45, 0xc1, 0xa9, 0x45,
	0x65, 0x99, 0xc9, 0xa9, 0x42, 0x31, 0x5c, 0xfc, 0x68, 0x16, 0x0a, 0x29, 0xeb, 0x21, 0xf9, 0x4f,
	0x0f, 0xbb, 0xe7, 0xa4, 0x54, 0xf0, 0x2b, 0x82, 0xb8, 0x39, 0x89, 0x0d, 0x2c, 0x6d, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x41, 0x26, 0x15, 0x44, 0x41, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterLeaderServiceClient is the client API for ClusterLeaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterLeaderServiceClient interface {
	ConfirmShardMap(ctx context.Context, in *ConfirmShardMapRequest, opts ...grpc.CallOption) (*ConfirmShardMapResponse, error)
}

type clusterLeaderServiceClient struct {
	cc *grpc.ClientConn
}

func NewClusterLeaderServiceClient(cc *grpc.ClientConn) ClusterLeaderServiceClient {
	return &clusterLeaderServiceClient{cc}
}

func (c *clusterLeaderServiceClient) ConfirmShardMap(ctx context.Context, in *ConfirmShardMapRequest, opts ...grpc.CallOption) (*ConfirmShardMapResponse, error) {
	out := new(ConfirmShardMapResponse)
	err := c.cc.Invoke(ctx, "/clusteproto.ClusterLeaderService/ConfirmShardMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterLeaderServiceServer is the server API for ClusterLeaderService service.
type ClusterLeaderServiceServer interface {
	ConfirmShardMap(context.Context, *ConfirmShardMapRequest) (*ConfirmShardMapResponse, error)
}

func RegisterClusterLeaderServiceServer(s *grpc.Server, srv ClusterLeaderServiceServer) {
	s.RegisterService(&_ClusterLeaderService_serviceDesc, srv)
}

func _ClusterLeaderService_ConfirmShardMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmShardMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterLeaderServiceServer).ConfirmShardMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusteproto.ClusterLeaderService/ConfirmShardMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterLeaderServiceServer).ConfirmShardMap(ctx, req.(*ConfirmShardMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterLeaderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clusteproto.ClusterLeaderService",
	HandlerType: (*ClusterLeaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmShardMap",
			Handler:    _ClusterLeaderService_ConfirmShardMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}
